name: Lint

on:
  - push
  - pull_request

permissions:
  contents: read
  pull-requests: read
  checks: write

jobs:
  lint:
    strategy:
      matrix:
        go-version: [ '1.20' ]
    name: Flake8
    uses: SanctumLabs/ci-workflows/.github/workflows/go-lint.yml@main
    with:
      go-version: ${{ matrix.go-version }}
